export const blogText = [
    {
        url: "/blog/kibble-caper",
        title: "The Great Kibble Heist",
        content: "<article><h1>The Great Kibble Heist</h1><p>The morning sun spilled through the kitchen window, painting golden stripes across the tile floor. It was quiet—too quiet. Garfield was dozing near his food bowl, his massive frame rising and falling like a furry mountain. His snoring echoed faintly, a deep rumble that signaled one thing: it was time to strike.</p><p>  You see, Garfield's food bowl isn't just a bowl. It's a treasure chest. A shimmering, aromatic monument to unfairness. His kibble—rich, savory, meaty—is clearly of higher quality than my own dry, crunchy pebbles. The humans claim it's because \"dogs need different nutrients.\" Lies. Lies to keep me oppressed. </p><p>  I crouched behind the leg of the table, tail flicking with anticipation. My ears twitched toward Garfield's snores. One eye cracked open—no movement. Good. The path was clear. I began my stealthy approach, paws gliding over the tile like whispers. Every step was calculated. Every sound measured. The mission was simple: infiltrate, acquire, escape.</p><p>  As I reached the bowl, a heavenly aroma rose up and wrapped around me like a hug. My stomach growled in betrayal. I dipped my paw in, fished out a single piece of kibble, and popped it into my mouth. The taste was divine—chicken, beef, and victory all in one bite. I savored it. I was unstoppable.</p><p>  That's when I heard the growl.</p><p>  My fur puffed out instantly. I turned, and there he was—Garfield, the guardian of the gourmet, his jowls quivering with righteous fury. He lumbered to his feet, ears back, eyes locked on me. The silence that followed was thick, heavy, almost cinematic. </p><p>  I didn't blink. Neither did he. Somewhere in the distance, a clock ticked. Then, he barked. Loudly. The sound echoed off the walls, rattling the dishes and surely alerting the humans upstairs. </p><p>  I grabbed another piece—pure instinct—and dashed for the counter. My paws scrambled, claws clicking, as Garfield charged. I launched myself upward, barely missing his snapping jaws, and landed on the counter with feline grace. From there, I turned to face him, tail flicking smugly.</p><p>  He barked again, this time more out of frustration than fury. I, of course, began to eat my stolen prize in plain sight. Slowly. Deliberately. Crunch by crunch.</p><p>  Eventually, the humans came down. \"Kitty! Garfield! What's going on?\" they shouted, separating us like children fighting over toys. Garfield sulked. I licked my paw innocently, pretending not to know what all the fuss was about. They refilled his bowl. I licked my lips.</p><p>  As they turned away, Garfield gave me one last glare, a low growl rumbling in his chest. I just blinked, slow and smug, before curling up on the counter for a nap. Justice had been served—and it tasted like chicken.</p></article>",
        media: "/src/media/kibble-caper.png",
        mediaAlt: "Image of cat stealing dog food"
    },
    {
        url: "/blog/rat",
        title: "The Rat Incident",
        content: "<article><h1>The Rat Incident</h1><p>It started as a normal afternoon—sunbeams across the floor, Garfield snoring, and me halfway through my third nap. Then, I heard it: the faint, frantic scurrying beneath the pantry. My ears twitched. My eyes opened. A thrill ran through me. Something was alive down there, and it wasn't supposed to be.</p><p>  I approached slowly, head low, muscles coiled. The sound came again—a soft squeak, the shuffle of tiny paws. My instincts screamed, *Hunter mode: engaged.* The world narrowed to a single point of focus. Every heartbeat pounded with purpose. I crouched, ready to strike.</p><p>  The rat made its mistake then. It darted into the open, just far enough for me to see its tail flick. That was all I needed. I lunged.</p><p>  The chase was glorious. We tore through the kitchen like a whirlwind of fur and fury. I knocked over a cereal box, Garfield woke up barking, and chaos reigned supreme. The rat tried to flee under the fridge, but I was faster. One swift pounce, a blur of claws and teeth, and the hunt was over.</p><p>  I stood there, victorious, tail high, rat in mouth. I felt powerful—magnificent even. This was proof of my worth, my skill, my divine purpose. Surely the humans would praise me for saving their pantry from the invader. So naturally, I decided to present my prize.</p><p>  I carried it proudly through the hallway, head held high. The humans' door was open just a crack. Perfect. I slipped in, careful not to make a sound. I laid the rat gently on the carpet, right by their shoes. A gift of gratitude. A token of my protection.</p><p>  But before I could admire my work, the lights flicked on. \"Kitty? What's that?\" My human's voice was a mix of confusion and disgust. I froze. I tried the innocent look—the wide eyes, the slow blink. Didn't work. \"Oh no,\" they groaned, \"is that a rat?! Kitty!\"</p><p>  They rushed to grab a towel, shooing me away as if I were the villain. I backed up, offended. Didn't they understand what I'd done for them? I saved them! I defended the home! And this was my reward—banishment from the bedroom.</p><p>  I sulked under the couch for an hour, licking my paws and muttering (silently, of course) about human ingratitude. Later, I retrieved the rat's tail from under the dresser and hid it beneath the bed. A trophy. A reminder.</p><p>  Someday, when they find it, they'll realize the truth. I am not just Kitty the cat. I am Kitty the conqueror.</p></article >", 
        media: "/src/media/cat-catch-rat.png",
        mediaAlt: "Image of cat catching rat"
    },
    {
        url: "/blog/bed",
        title: "The Bed Conquest",
        content: "<article><h1>The Bed Conquest</h1><p>  It's funny how humans think they own the bed. Every night, they crawl into it like they're the rulers of some kingdom, unaware that I, Kitty, am the true sovereign of this domain. My reign begins when the lights go out.</p><p>  Tonight, I waited patiently until they drifted off. Then, as stealthy as a shadow, I climbed onto the bed. The sheets were still warm, the air thick with the scent of comfort. Perfect conditions for an invasion.</p><p>  I circled three times (the proper royal protocol), then settled right in the center—where my presence would be most disruptive. I stretched luxuriously, paws extended, tail flicking. The human murmured something in his sleep. I ignored him. He would adapt.</p><p>  Minutes passed. Then came the inevitable attempt at resistance. The blanket shifted. A gentle shove against my side. \"Move over, Kitty,\" he whispered. I went limp immediately. My weight quadrupled. I became immovable, a fuzzy boulder of defiance.</p><p>  He sighed and gave up, rolling to the edge of the bed. Victory.</p><p>  I purred, low and steady, like a queen satisfied with her throne. Garfield tried to join at one point—he leapt up clumsily, snorted, and flopped onto my tail. I gave him a swift paw to the face. He yelped and retreated to his bed on the floor, where he belonged.</p><p>  The night stretched on peacefully after that. I dreamed of sunbeams, tuna cans, and endless pillows. Occasionally, the human would stir, muttering about \"fur everywhere\" or \"not again,\" but I didn't budge. </p><p>  By morning, he woke up cramped on the very edge, while I lay sprawled like royalty. I blinked at him lazily, stretched, and yawned. He groaned. I purred. </p><p>  As he got up to make breakfast, I stayed right where I was, basking in my victory. Garfield trotted in, drooling, and glanced up at me with envy. I smirked, because some conquests are eternal—and this bed, this warm and glorious fortress, belongs to me.</p></article>",
        media: "/src/media/sneep.png",
        mediaAlt: "Image of cat sleepeing"
    }
]